# Generated by Django 5.1.1 on 2024-10-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyUsers', '0003_my_user_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_user',
            old_name='date',
            new_name='created_date',
        ),
    ]
